[client]
showSidebarNavigation = false

[theme]
backgroundColor = '#1b263b'
secondaryBackgroundColor = '#0d1b2a'
textColor = '#FFFFFF'
font = "serif"

[theme.sidebar]
backgroundColor = '#0d1b2a'
textColor = '#FFFFFF'